import { build as esbuild } from "esbuild";
import { build as viteBuild } from "vite";
import { rm, readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve } from "node:path";

// server deps to bundle to reduce openat(2) syscalls
// which helps cold start times
const allowlist = [
  "@google/generative-ai",
  "axios",
  "cors",
  "csv-parse",
  "csv-parse/sync",
  "date-fns",
  "dotenv",
  "drizzle-orm",
  "drizzle-orm/sql-js",
  "drizzle-zod",
  "express",
  "express-rate-limit",
  "express-session",
  "helmet",
  "jsonwebtoken",
  "memorystore",
  "multer",
  "nanoid",
  "nodemailer",
  "openai",
  "passport",
  "passport-local",
  "sql.js",
  "stripe",
  "uuid",
  "ws",
  "xlsx",
  "zod",
  "zod-validation-error",
];

async function buildAll() {
  await rm("dist", { recursive: true, force: true });

  console.log("building client...");
  await viteBuild();

  // Generate a wasm-loader module that embeds sql-wasm.wasm as base64.
  // This avoids __dirname + fs path issues in Vercel Lambda where includeFiles
  // doesn't reliably copy files into the Lambda package for prebuilt deployments.
  console.log("embedding sql-wasm.wasm as base64...");
  const wasmSrc = resolve("node_modules/sql.js/dist/sql-wasm.wasm");
  if (!existsSync(wasmSrc)) {
    throw new Error("sql-wasm.wasm not found at " + wasmSrc);
  }
  const wasmBuffer = await readFile(wasmSrc);
  const wasmBase64 = wasmBuffer.toString("base64");
  const loaderCode = `// Auto-generated by build.ts — DO NOT EDIT
// Embeds sql-wasm.wasm as base64 to avoid Lambda filesystem path issues
export const wasmBase64 = "${wasmBase64}";
export const wasmBinary = Buffer.from(wasmBase64, "base64");
`;
  await mkdir("server/generated", { recursive: true });
  await writeFile("server/generated/sql-wasm-loader.ts", loaderCode, "utf-8");
  console.log(`embedded sql-wasm.wasm (${Math.round(wasmBase64.length / 1024)}KB base64)`);

  // Embed dist/public/index.html as a TS constant so the Vercel Lambda
  // never needs to read from the filesystem (Lambda fs paths are unreliable).
  console.log("embedding index.html as constant...");
  const indexHtmlSrc = resolve("dist/public/index.html");
  if (!existsSync(indexHtmlSrc)) {
    throw new Error("dist/public/index.html not found — run vite build first");
  }
  const indexHtmlContent = await readFile(indexHtmlSrc, "utf-8");
  const indexHtmlEscaped = JSON.stringify(indexHtmlContent);
  const indexHtmlLoader = `// Auto-generated by build.ts — DO NOT EDIT\n// Embeds dist/public/index.html as a string constant\nexport const INDEX_HTML = ${indexHtmlEscaped};\n`;
  await writeFile("server/generated/index-html-loader.ts", indexHtmlLoader, "utf-8");
  console.log(`embedded index.html (${Math.round(indexHtmlContent.length / 1024)}KB)`);

  console.log("building server...");
  const pkg = JSON.parse(await readFile("package.json", "utf-8"));
  const allDeps = [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.devDependencies || {}),
  ];
  // Always treat these as external — they have native binaries or can't be bundled
  const forceExternal = [
    'playwright', 'playwright-core', 'playwright-chromium',
    'chromium-bidi', '@playwright/test',
    'better-sqlite3', 'pg', 'bcryptjs',
  ];
  const externals = [
    ...forceExternal,
    ...allDeps.filter((dep) => !allowlist.includes(dep)),
  ].filter((v, i, a) => a.indexOf(v) === i);

  // Build 1: pplx.app / local — uses httpServer.listen()
  await esbuild({
    entryPoints: ["server/index.ts"],
    platform: "node",
    bundle: true,
    format: "cjs",
    outfile: "dist/index.cjs",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    minify: true,
    external: externals,
    logLevel: "info",
  });

  // Build 2: Vercel Lambda — exports handler, no listen()
  console.log("building vercel handler...");
  await esbuild({
    entryPoints: ["server/vercel-handler.ts"],
    platform: "node",
    bundle: true,
    format: "cjs",
    outfile: "dist/vercel-handler.cjs",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    minify: true,
    external: externals,
    logLevel: "info",
  });
}

buildAll().catch((err) => {
  console.error(err);
  process.exit(1);
});
